eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://${ZIPKIN_SERVER:localhost}:9411
    sender:
      type: rabbit
  rabbitmq:
    host: ${RABBIT_SERVER:localhost}

