server:
  port: 8082

spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:mysql://${holiday-booker-db:localhost}:3308/holiday-booker-db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop